// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzfmzzyjxriiuwagweay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Zm16enlqeHJpaXV3YWd3ZWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDY3MDUsImV4cCI6MjA3MjQyMjcwNX0.wX7-UOQ3YugKtoIj7PGMrP1b2x5XJEBoRs__DWzd48Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});